# .github/workflows/dotnet-ci.yml

name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: ProductDb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Restore dependencies
        run: dotnet restore Product.API.sln

      - name: Build
        run: dotnet build Product.API.sln --configuration Release --no-restore

      - name: Wait for Redis
        run: |
          echo "Waiting for Redis to be ready..."
          count=0
          while ! redis-cli -h localhost -p 6379 ping | grep -q PONG; do
            if [ $count -gt 20 ]; then
              echo "Redis did not become ready in time."
              exit 1
            fi
            sleep 5
            count=$((count+1))
            echo "Still waiting for Redis... attempt $count"
          done
          echo "Redis is ready!"

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          count=0
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            if [ $count -gt 20 ]; then
              echo "PostgreSQL did not become ready in time."
              exit 1
            fi
            sleep 5
            count=$((count+1))
            echo "Still waiting for PostgreSQL... attempt $count"
          done
          echo "PostgreSQL is ready!"

      - name: Test
        run: dotnet test Product.API.sln --configuration Release --no-build --verbosity normal
        env:
          ConnectionStrings__Redis: "localhost:6379"
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=ProductDb;Username=postgres;Password=yourpassword"
